// <auto-generated />
using LutryShop.ProductApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LutryShop.ProductApi.Migrations
{
    [DbContext(typeof(MySqlContext))]
    [Migration("20240226223918_seeding")]
    partial class seeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LutryShop.ProductApi.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryName = "Seed Category Name 1",
                            Description = "Seed Description 1",
                            ImageURL = "Seed ImageURL 1",
                            Name = "Seed Name 1",
                            Price = 1m
                        },
                        new
                        {
                            Id = 2L,
                            CategoryName = "Seed Category Name 2",
                            Description = "Seed Description 2",
                            ImageURL = "Seed ImageURL 2",
                            Name = "Seed Name 2",
                            Price = 2m
                        },
                        new
                        {
                            Id = 3L,
                            CategoryName = "Seed Category Name 3",
                            Description = "Seed Description 3",
                            ImageURL = "Seed ImageURL 3",
                            Name = "Seed Name 3",
                            Price = 3m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "Seed Category Name 4",
                            Description = "Seed Description 4",
                            ImageURL = "Seed ImageURL 4",
                            Name = "Seed Name 4",
                            Price = 4m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
